import { 
    FETCH_CAT_LOADING, 
    FETCH_CAT_SUCCESS, 
    FETCH_CAT_ERROR, 
    ADOPT_CAT_LOADING, 
    ADOPT_CAT_ERROR
} from './cat.action'; 

import { 
    FETCH_DOG_LOADING, 
    FETCH_DOG_SUCCESS, 
    FETCH_DOG_ERROR, 
    ADOPT_DOG_LOADING, 
    ADOPT_DOG_ERROR
} from './dog.action'; 

export const actions = {
    FETCH_CAT_LOADING, 
    FETCH_CAT_SUCCESS, 
    FETCH_CAT_ERROR, 
    ADOPT_CAT_LOADING, 
    ADOPT_CAT_ERROR, 
    FETCH_DOG_LOADING, 
    FETCH_DOG_SUCCESS, 
    FETCH_DOG_ERROR,
    ADOPT_DOG_LOADING, 
    ADOPT_CAT_ERROR 
}; 